---
- name: Install docker and docker-compose
  hosts: 
    - webservers
    - apiservers
  become: true
  roles:
    - docker

- name: Web servers setup
  hosts: webservers
  become: true
  roles:
    - web

- name: Database server and API setup
  hosts: apiservers
  become: true
  roles:
    - api
    - db